#ifndef __USB_DESC_H
#define __USB_DESC_H

// "Table 9-5. Descriptor Types" at 251 page in usb_20.pdf
#define USB_DESCRIPTOR_TYPE_DEVICE						0x01
#define USB_DESCRIPTOR_TYPE_CONFIGURATION				0x02
#define USB_DESCRIPTOR_TYPE_STRING						0x03
#define USB_DESCRIPTOR_TYPE_INTERFACE					0x04
#define USB_DESCRIPTOR_TYPE_ENDPOINT					0x05
//#define USB_DESCRIPTOR_TYPE_DEVICE_QUALIFIER			0x06
//#define USB_DESCRIPTOR_TYPE_OTHER_SPEED_CONFIGURATION	0x07
//#define USB_DESCRIPTOR_TYPE_INTERFACE_POWER			0x08

#define HID_DESCRIPTOR_TYPE			0x21

#define JOYSTICK_SIZ_HID_DESC		0x09
#define JOYSTICK_OFF_HID_DESC		0x12

#define JOYSTICK_SIZ_DEVICE_DESC	18
#define JOYSTICK_SIZ_CONFIG_DESC	34
#define JOYSTICK_SIZ_REPORT_DESC	52

#define JOYSTICK_SIZ_STRING_LANGID	4
#define JOYSTICK_SIZ_STRING_VENDOR	38
#define JOYSTICK_SIZ_STRING_PRODUCT	30
#define JOYSTICK_SIZ_STRING_SERIAL	26

extern const uint8_t Joystick_DeviceDescriptor[JOYSTICK_SIZ_DEVICE_DESC];
extern const uint8_t Joystick_ConfigDescriptor[JOYSTICK_SIZ_CONFIG_DESC];
extern const uint8_t Joystick_ReportDescriptor[JOYSTICK_SIZ_REPORT_DESC];
extern const uint8_t Joystick_StringLangID[JOYSTICK_SIZ_STRING_LANGID];
extern const uint8_t Joystick_StringVendor[JOYSTICK_SIZ_STRING_VENDOR];
extern const uint8_t Joystick_StringProduct[JOYSTICK_SIZ_STRING_PRODUCT];
extern uint8_t Joystick_StringSerial[JOYSTICK_SIZ_STRING_SERIAL];

#endif /* __USB_DESC_H */
